name: DECENT
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch
  - torchvision
  - scikit-learn
  - torchaudio
  - matplotlib
  - captum
  - ipykernel
  - seaborn
